### ISSUE TITLE
"rails g azul_pay_button" command is not working

### ISSUE THREAD

**Issue by gg7star** [iCueto/Azul-Pay-Button#3]
I tried to run "rails g azul_pay_button" command. but nothing. it didn't work.
I used Ruby 2.3.1p112 and Rails 5.1.5.
How can I use this?

**Comment by gg7star** [comment]
After rebooted pc, I ran above command. so it's working now.
I wrote config info and re-run rails app. and I clicked "Pay with Azul payment page".
But I got issue "INVALID_AUTH:AuthHash" on"https://pruebas.azul.com.do/PaymentPage/Error.aspx?sec" url.
How can I fix this issue?

**Comment by gg7star** [comment]
no response.

**Comment by iCueto** [comment]
Ufff, sorry, I've totally forgotten that, Apologies.

The Azul's people, have a lot of errors and the documentation don't work in any cases, due to updates on their platforms, and thank to the aristocracy, is almost imposible build a working product. 

In other forums I've asked for someone have an updated documentation or a working Api key for test the gem. I've not received any response.

If you want you can help me to fix that bug, you can contribute to this gem.

Don't be afraid to get your hands dirty. All contributions are welcome. Thanks. 🙃
